#ChipScope Core Inserter Project File Version 3.0
#Wed Nov 26 15:21:26 CET 2025
Project.device.designInputFile=/home/user/_WORKSPACE_/kedziorno/mlx90640_fpga/test1_cs.ngc
Project.device.designOutputFile=/home/user/_WORKSPACE_/kedziorno/mlx90640_fpga/test1_cs.ngc
Project.device.deviceFamily=13
Project.device.enableRPMs=true
Project.device.outputDirectory=/home/user/_WORKSPACE_/kedziorno/mlx90640_fpga/_ngo
Project.device.useSRL16=true
Project.filter.dimension=8
Project.filter<0>=*pixos*dia*
Project.filter<1>=*pixos*
Project.filter<2>=*pixos_do*
Project.filter<3>=
Project.filter<4>=*_do*
Project.filter<5>=_do*
Project.filter<6>=_do
Project.filter<7>=*clock*
Project.icon.boundaryScanChain=1
Project.icon.enableExtTriggerIn=false
Project.icon.enableExtTriggerOut=false
Project.icon.triggerInPinName=
Project.icon.triggerOutPinName=
Project.unit.dimension=1
Project.unit<0>.clockChannel=i_clock_BUFGP
Project.unit<0>.clockEdge=Rising
Project.unit<0>.dataChannel<0>=tfm_inst inst_CalculatePixOS CalculatePixGain_do<0>
Project.unit<0>.dataChannel<10>=tfm_inst inst_CalculatePixOS CalculatePixGain_do<10>
Project.unit<0>.dataChannel<11>=tfm_inst inst_CalculatePixOS CalculatePixGain_do<11>
Project.unit<0>.dataChannel<12>=tfm_inst inst_CalculatePixOS CalculatePixGain_do<12>
Project.unit<0>.dataChannel<13>=tfm_inst inst_CalculatePixOS CalculatePixGain_do<13>
Project.unit<0>.dataChannel<14>=tfm_inst inst_CalculatePixOS CalculatePixGain_do<14>
Project.unit<0>.dataChannel<15>=tfm_inst inst_CalculatePixOS CalculatePixGain_do<15>
Project.unit<0>.dataChannel<16>=tfm_inst inst_CalculatePixOS CalculatePixGain_do<16>
Project.unit<0>.dataChannel<17>=tfm_inst inst_CalculatePixOS CalculatePixGain_do<17>
Project.unit<0>.dataChannel<18>=tfm_inst inst_CalculatePixOS CalculatePixGain_do<18>
Project.unit<0>.dataChannel<19>=tfm_inst inst_CalculatePixOS CalculatePixGain_do<19>
Project.unit<0>.dataChannel<1>=tfm_inst inst_CalculatePixOS CalculatePixGain_do<1>
Project.unit<0>.dataChannel<20>=tfm_inst inst_CalculatePixOS CalculatePixGain_do<20>
Project.unit<0>.dataChannel<21>=tfm_inst inst_CalculatePixOS CalculatePixGain_do<21>
Project.unit<0>.dataChannel<22>=tfm_inst inst_CalculatePixOS CalculatePixGain_do<22>
Project.unit<0>.dataChannel<23>=tfm_inst inst_CalculatePixOS CalculatePixGain_do<23>
Project.unit<0>.dataChannel<24>=tfm_inst inst_CalculatePixOS CalculatePixGain_do<24>
Project.unit<0>.dataChannel<25>=tfm_inst inst_CalculatePixOS CalculatePixGain_do<25>
Project.unit<0>.dataChannel<26>=tfm_inst inst_CalculatePixOS CalculatePixGain_do<26>
Project.unit<0>.dataChannel<27>=tfm_inst inst_CalculatePixOS CalculatePixGain_do<27>
Project.unit<0>.dataChannel<28>=tfm_inst inst_CalculatePixOS CalculatePixGain_do<28>
Project.unit<0>.dataChannel<29>=tfm_inst inst_CalculatePixOS CalculatePixGain_do<29>
Project.unit<0>.dataChannel<2>=tfm_inst inst_CalculatePixOS CalculatePixGain_do<2>
Project.unit<0>.dataChannel<30>=tfm_inst inst_CalculatePixOS CalculatePixGain_do<30>
Project.unit<0>.dataChannel<31>=tfm_inst inst_CalculatePixOS CalculatePixGain_do<31>
Project.unit<0>.dataChannel<3>=tfm_inst inst_CalculatePixOS CalculatePixGain_do<3>
Project.unit<0>.dataChannel<4>=tfm_inst inst_CalculatePixOS CalculatePixGain_do<4>
Project.unit<0>.dataChannel<5>=tfm_inst inst_CalculatePixOS CalculatePixGain_do<5>
Project.unit<0>.dataChannel<6>=tfm_inst inst_CalculatePixOS CalculatePixGain_do<6>
Project.unit<0>.dataChannel<7>=tfm_inst inst_CalculatePixOS CalculatePixGain_do<7>
Project.unit<0>.dataChannel<8>=tfm_inst inst_CalculatePixOS CalculatePixGain_do<8>
Project.unit<0>.dataChannel<9>=tfm_inst inst_CalculatePixOS CalculatePixGain_do<9>
Project.unit<0>.dataDepth=2048
Project.unit<0>.dataEqualsTrigger=true
Project.unit<0>.dataPortWidth=32
Project.unit<0>.enableGaps=false
Project.unit<0>.enableStorageQualification=true
Project.unit<0>.enableTimestamps=false
Project.unit<0>.timestampDepth=0
Project.unit<0>.timestampWidth=0
Project.unit<0>.triggerChannel<0><0>=tfm_inst/inst_CalculatePixOS/dia<0>
Project.unit<0>.triggerChannel<0><10>=tfm_inst/inst_CalculatePixOS/dia<10>
Project.unit<0>.triggerChannel<0><11>=tfm_inst/inst_CalculatePixOS/dia<11>
Project.unit<0>.triggerChannel<0><12>=tfm_inst/inst_CalculatePixOS/dia<12>
Project.unit<0>.triggerChannel<0><13>=tfm_inst/inst_CalculatePixOS/dia<13>
Project.unit<0>.triggerChannel<0><14>=tfm_inst/inst_CalculatePixOS/dia<14>
Project.unit<0>.triggerChannel<0><15>=tfm_inst/inst_CalculatePixOS/dia<15>
Project.unit<0>.triggerChannel<0><16>=tfm_inst/inst_CalculatePixOS/dia<16>
Project.unit<0>.triggerChannel<0><17>=tfm_inst/inst_CalculatePixOS/dia<17>
Project.unit<0>.triggerChannel<0><18>=tfm_inst/inst_CalculatePixOS/dia<18>
Project.unit<0>.triggerChannel<0><19>=tfm_inst/inst_CalculatePixOS/dia<19>
Project.unit<0>.triggerChannel<0><1>=tfm_inst/inst_CalculatePixOS/dia<1>
Project.unit<0>.triggerChannel<0><20>=tfm_inst/inst_CalculatePixOS/dia<20>
Project.unit<0>.triggerChannel<0><21>=tfm_inst/inst_CalculatePixOS/dia<21>
Project.unit<0>.triggerChannel<0><22>=tfm_inst/inst_CalculatePixOS/dia<22>
Project.unit<0>.triggerChannel<0><23>=tfm_inst/inst_CalculatePixOS/dia<23>
Project.unit<0>.triggerChannel<0><24>=tfm_inst/inst_CalculatePixOS/dia<24>
Project.unit<0>.triggerChannel<0><25>=tfm_inst/inst_CalculatePixOS/dia<25>
Project.unit<0>.triggerChannel<0><26>=tfm_inst/inst_CalculatePixOS/dia<26>
Project.unit<0>.triggerChannel<0><27>=tfm_inst/inst_CalculatePixOS/dia<27>
Project.unit<0>.triggerChannel<0><28>=tfm_inst/inst_CalculatePixOS/dia<28>
Project.unit<0>.triggerChannel<0><29>=tfm_inst/inst_CalculatePixOS/dia<29>
Project.unit<0>.triggerChannel<0><2>=tfm_inst/inst_CalculatePixOS/dia<2>
Project.unit<0>.triggerChannel<0><30>=tfm_inst/inst_CalculatePixOS/dia<30>
Project.unit<0>.triggerChannel<0><31>=tfm_inst/inst_CalculatePixOS/dia<31>
Project.unit<0>.triggerChannel<0><3>=tfm_inst/inst_CalculatePixOS/dia<3>
Project.unit<0>.triggerChannel<0><4>=tfm_inst/inst_CalculatePixOS/dia<4>
Project.unit<0>.triggerChannel<0><5>=tfm_inst/inst_CalculatePixOS/dia<5>
Project.unit<0>.triggerChannel<0><6>=tfm_inst/inst_CalculatePixOS/dia<6>
Project.unit<0>.triggerChannel<0><7>=tfm_inst/inst_CalculatePixOS/dia<7>
Project.unit<0>.triggerChannel<0><8>=tfm_inst/inst_CalculatePixOS/dia<8>
Project.unit<0>.triggerChannel<0><9>=tfm_inst/inst_CalculatePixOS/dia<9>
Project.unit<0>.triggerConditionCountWidth=0
Project.unit<0>.triggerMatchCount<0>=1
Project.unit<0>.triggerMatchCountWidth<0><0>=0
Project.unit<0>.triggerMatchType<0><0>=1
Project.unit<0>.triggerPortCount=1
Project.unit<0>.triggerPortIsData<0>=true
Project.unit<0>.triggerPortWidth<0>=32
Project.unit<0>.triggerSequencerLevels=16
Project.unit<0>.triggerSequencerType=1
Project.unit<0>.type=ilapro
