#ChipScope Core Inserter Project File Version 3.0
#Fri Nov 28 15:25:50 CET 2025
Project.device.designInputFile=/home/user/_WORKSPACE_/kedziorno/mlx90640_fpga/test1_cs.ngc
Project.device.designOutputFile=/home/user/_WORKSPACE_/kedziorno/mlx90640_fpga/test1_cs.ngc
Project.device.deviceFamily=12
Project.device.enableRPMs=true
Project.device.outputDirectory=/home/user/_WORKSPACE_/kedziorno/mlx90640_fpga/_ngo
Project.device.useSRL16=true
Project.filter.dimension=19
Project.filter<0>=*o_do*
Project.filter<10>=*dia**
Project.filter<11>=*divfprdy*
Project.filter<12>=dia*
Project.filter<13>=mulfprdy*
Project.filter<14>=addfprdy*
Project.filter<15>=*subfprdy*
Project.filter<16>=/tfm_inst/inst_CalculatePixOS/sub*
Project.filter<17>=/tfm_inst/inst_CalculatePixOS/sub
Project.filter<18>=/tfm_inst/inst_CalculatePixOS/subfprdy
Project.filter<1>=*doa*
Project.filter<2>=
Project.filter<3>=*clock*
Project.filter<4>=*rom_cons*
Project.filter<5>=divfpr*
Project.filter<6>=divfprdy*
Project.filter<7>=divfpr
Project.filter<8>=*dia*
Project.filter<9>=*write_enable*
Project.icon.boundaryScanChain=1
Project.icon.enableExtTriggerIn=false
Project.icon.enableExtTriggerOut=false
Project.icon.triggerInPinName=
Project.icon.triggerOutPinName=
Project.unit.dimension=1
Project.unit<0>.clockChannel=tfm_inst inst_CalculatePixOS inst_ExtractKvParameters i_clock
Project.unit<0>.clockEdge=Rising
Project.unit<0>.dataChannel<0>=tfm_inst inst_CalculatePixOS inst_ExtractKvParameters o_do<0>
Project.unit<0>.dataChannel<10>=tfm_inst inst_CalculatePixOS inst_ExtractKvParameters o_do<10>
Project.unit<0>.dataChannel<11>=tfm_inst inst_CalculatePixOS inst_ExtractKvParameters o_do<11>
Project.unit<0>.dataChannel<12>=tfm_inst inst_CalculatePixOS inst_ExtractKvParameters o_do<12>
Project.unit<0>.dataChannel<13>=tfm_inst inst_CalculatePixOS inst_ExtractKvParameters o_do<13>
Project.unit<0>.dataChannel<14>=tfm_inst inst_CalculatePixOS inst_ExtractKvParameters o_do<14>
Project.unit<0>.dataChannel<15>=tfm_inst inst_CalculatePixOS inst_ExtractKvParameters o_do<15>
Project.unit<0>.dataChannel<16>=tfm_inst inst_CalculatePixOS inst_ExtractKvParameters o_do<16>
Project.unit<0>.dataChannel<17>=tfm_inst inst_CalculatePixOS inst_ExtractKvParameters o_do<17>
Project.unit<0>.dataChannel<18>=tfm_inst inst_CalculatePixOS inst_ExtractKvParameters o_do<18>
Project.unit<0>.dataChannel<19>=tfm_inst inst_CalculatePixOS inst_ExtractKvParameters o_do<19>
Project.unit<0>.dataChannel<1>=tfm_inst inst_CalculatePixOS inst_ExtractKvParameters o_do<1>
Project.unit<0>.dataChannel<20>=tfm_inst inst_CalculatePixOS inst_ExtractKvParameters o_do<20>
Project.unit<0>.dataChannel<21>=tfm_inst inst_CalculatePixOS inst_ExtractKvParameters o_do<21>
Project.unit<0>.dataChannel<22>=tfm_inst inst_CalculatePixOS inst_ExtractKvParameters o_do<22>
Project.unit<0>.dataChannel<23>=tfm_inst inst_CalculatePixOS inst_ExtractKvParameters o_do<23>
Project.unit<0>.dataChannel<24>=tfm_inst inst_CalculatePixOS inst_ExtractKvParameters o_do<24>
Project.unit<0>.dataChannel<25>=tfm_inst inst_CalculatePixOS inst_ExtractKvParameters o_do<25>
Project.unit<0>.dataChannel<26>=tfm_inst inst_CalculatePixOS inst_ExtractKvParameters o_do<26>
Project.unit<0>.dataChannel<27>=tfm_inst inst_CalculatePixOS inst_ExtractKvParameters o_do<27>
Project.unit<0>.dataChannel<28>=tfm_inst inst_CalculatePixOS inst_ExtractKvParameters o_do<28>
Project.unit<0>.dataChannel<29>=tfm_inst inst_CalculatePixOS inst_ExtractKvParameters o_do<29>
Project.unit<0>.dataChannel<2>=tfm_inst inst_CalculatePixOS inst_ExtractKvParameters o_do<2>
Project.unit<0>.dataChannel<30>=tfm_inst inst_CalculatePixOS inst_ExtractKvParameters o_do<30>
Project.unit<0>.dataChannel<31>=tfm_inst inst_CalculatePixOS inst_ExtractKvParameters o_do<31>
Project.unit<0>.dataChannel<3>=tfm_inst inst_CalculatePixOS inst_ExtractKvParameters o_do<3>
Project.unit<0>.dataChannel<4>=tfm_inst inst_CalculatePixOS inst_ExtractKvParameters o_do<4>
Project.unit<0>.dataChannel<5>=tfm_inst inst_CalculatePixOS inst_ExtractKvParameters o_do<5>
Project.unit<0>.dataChannel<6>=tfm_inst inst_CalculatePixOS inst_ExtractKvParameters o_do<6>
Project.unit<0>.dataChannel<7>=tfm_inst inst_CalculatePixOS inst_ExtractKvParameters o_do<7>
Project.unit<0>.dataChannel<8>=tfm_inst inst_CalculatePixOS inst_ExtractKvParameters o_do<8>
Project.unit<0>.dataChannel<9>=tfm_inst inst_CalculatePixOS inst_ExtractKvParameters o_do<9>
Project.unit<0>.dataDepth=16384
Project.unit<0>.dataEqualsTrigger=false
Project.unit<0>.dataPortWidth=32
Project.unit<0>.enableGaps=false
Project.unit<0>.enableStorageQualification=true
Project.unit<0>.enableTimestamps=false
Project.unit<0>.timestampDepth=0
Project.unit<0>.timestampWidth=0
Project.unit<0>.triggerChannel<0><0>=tfm_inst inst_CalculatePixOS inst_ExtractKvParameters i_clock
Project.unit<0>.triggerConditionCountWidth=0
Project.unit<0>.triggerMatchCount<0>=1
Project.unit<0>.triggerMatchCountWidth<0><0>=0
Project.unit<0>.triggerMatchType<0><0>=1
Project.unit<0>.triggerPortCount=1
Project.unit<0>.triggerPortIsData<0>=true
Project.unit<0>.triggerPortWidth<0>=1
Project.unit<0>.triggerSequencerLevels=16
Project.unit<0>.triggerSequencerType=1
Project.unit<0>.type=ilapro
