#ChipScope Core Inserter Project File Version 3.0
#Wed Nov 26 23:15:35 CET 2025
Project.device.designInputFile=/home/user/_WORKSPACE_/kedziorno/mlx90640_fpga/test1_cs.ngc
Project.device.designOutputFile=/home/user/_WORKSPACE_/kedziorno/mlx90640_fpga/test1_cs.ngc
Project.device.deviceFamily=13
Project.device.enableRPMs=true
Project.device.outputDirectory=/home/user/_WORKSPACE_/kedziorno/mlx90640_fpga/_ngo
Project.device.useSRL16=true
Project.filter.dimension=19
Project.filter<0>=divfpr*
Project.filter<10>=addfprdy*
Project.filter<11>=*subfprdy*
Project.filter<12>=/tfm_inst/inst_CalculatePixOS/sub*
Project.filter<13>=/tfm_inst/inst_CalculatePixOS/sub
Project.filter<14>=/tfm_inst/inst_CalculatePixOS/subfprdy
Project.filter<15>=*tfm_inst/inst_CalculatePixOS/subfprdy
Project.filter<16>=CH\:0\t/tfm_inst/inst_CalculatePixOS/subfprdy
Project.filter<17>=*PixOS*subfp*
Project.filter<18>=*pixos*subfp*
Project.filter<1>=divfprdy*
Project.filter<2>=divfpr
Project.filter<3>=
Project.filter<4>=*dia*
Project.filter<5>=*write_enable*
Project.filter<6>=*dia**
Project.filter<7>=*divfprdy*
Project.filter<8>=dia*
Project.filter<9>=mulfprdy*
Project.icon.boundaryScanChain=1
Project.icon.enableExtTriggerIn=false
Project.icon.enableExtTriggerOut=false
Project.icon.triggerInPinName=
Project.icon.triggerOutPinName=
Project.unit.dimension=1
Project.unit<0>.clockChannel=tfm_inst inst_CalculatePixOS inst_ExtractKvParameters divfprdy
Project.unit<0>.clockEdge=Rising
Project.unit<0>.dataChannel<0>=tfm_inst inst_CalculatePixOS inst_ExtractKvParameters divfpr<0>
Project.unit<0>.dataChannel<10>=tfm_inst inst_CalculatePixOS inst_ExtractKvParameters divfpr<10>
Project.unit<0>.dataChannel<11>=tfm_inst inst_CalculatePixOS inst_ExtractKvParameters divfpr<11>
Project.unit<0>.dataChannel<12>=tfm_inst inst_CalculatePixOS inst_ExtractKvParameters divfpr<12>
Project.unit<0>.dataChannel<13>=tfm_inst inst_CalculatePixOS inst_ExtractKvParameters divfpr<13>
Project.unit<0>.dataChannel<14>=tfm_inst inst_CalculatePixOS inst_ExtractKvParameters divfpr<14>
Project.unit<0>.dataChannel<15>=tfm_inst inst_CalculatePixOS inst_ExtractKvParameters divfpr<15>
Project.unit<0>.dataChannel<16>=tfm_inst inst_CalculatePixOS inst_ExtractKvParameters divfpr<16>
Project.unit<0>.dataChannel<17>=tfm_inst inst_CalculatePixOS inst_ExtractKvParameters divfpr<17>
Project.unit<0>.dataChannel<18>=tfm_inst inst_CalculatePixOS inst_ExtractKvParameters divfpr<18>
Project.unit<0>.dataChannel<19>=tfm_inst inst_CalculatePixOS inst_ExtractKvParameters divfpr<19>
Project.unit<0>.dataChannel<1>=tfm_inst inst_CalculatePixOS inst_ExtractKvParameters divfpr<1>
Project.unit<0>.dataChannel<20>=tfm_inst inst_CalculatePixOS inst_ExtractKvParameters divfpr<20>
Project.unit<0>.dataChannel<21>=tfm_inst inst_CalculatePixOS inst_ExtractKvParameters divfpr<21>
Project.unit<0>.dataChannel<22>=tfm_inst inst_CalculatePixOS inst_ExtractKvParameters divfpr<22>
Project.unit<0>.dataChannel<23>=tfm_inst inst_CalculatePixOS inst_ExtractKvParameters divfpr<23>
Project.unit<0>.dataChannel<24>=tfm_inst inst_CalculatePixOS inst_ExtractKvParameters divfpr<24>
Project.unit<0>.dataChannel<25>=tfm_inst inst_CalculatePixOS inst_ExtractKvParameters divfpr<25>
Project.unit<0>.dataChannel<26>=tfm_inst inst_CalculatePixOS inst_ExtractKvParameters divfpr<26>
Project.unit<0>.dataChannel<27>=tfm_inst inst_CalculatePixOS inst_ExtractKvParameters divfpr<27>
Project.unit<0>.dataChannel<28>=tfm_inst inst_CalculatePixOS inst_ExtractKvParameters divfpr<28>
Project.unit<0>.dataChannel<29>=tfm_inst inst_CalculatePixOS inst_ExtractKvParameters divfpr<29>
Project.unit<0>.dataChannel<2>=tfm_inst inst_CalculatePixOS inst_ExtractKvParameters divfpr<2>
Project.unit<0>.dataChannel<30>=tfm_inst inst_CalculatePixOS inst_ExtractKvParameters divfpr<30>
Project.unit<0>.dataChannel<31>=tfm_inst inst_CalculatePixOS inst_ExtractKvParameters divfpr<31>
Project.unit<0>.dataChannel<3>=tfm_inst inst_CalculatePixOS inst_ExtractKvParameters divfpr<3>
Project.unit<0>.dataChannel<4>=tfm_inst inst_CalculatePixOS inst_ExtractKvParameters divfpr<4>
Project.unit<0>.dataChannel<5>=tfm_inst inst_CalculatePixOS inst_ExtractKvParameters divfpr<5>
Project.unit<0>.dataChannel<6>=tfm_inst inst_CalculatePixOS inst_ExtractKvParameters divfpr<6>
Project.unit<0>.dataChannel<7>=tfm_inst inst_CalculatePixOS inst_ExtractKvParameters divfpr<7>
Project.unit<0>.dataChannel<8>=tfm_inst inst_CalculatePixOS inst_ExtractKvParameters divfpr<8>
Project.unit<0>.dataChannel<9>=tfm_inst inst_CalculatePixOS inst_ExtractKvParameters divfpr<9>
Project.unit<0>.dataDepth=2048
Project.unit<0>.dataEqualsTrigger=false
Project.unit<0>.dataPortWidth=32
Project.unit<0>.enableGaps=false
Project.unit<0>.enableStorageQualification=true
Project.unit<0>.enableTimestamps=false
Project.unit<0>.timestampDepth=0
Project.unit<0>.timestampWidth=0
Project.unit<0>.triggerChannel<0><0>=tfm_inst inst_CalculatePixOS inst_ExtractKvParameters divfprdy
Project.unit<0>.triggerConditionCountWidth=0
Project.unit<0>.triggerMatchCount<0>=1
Project.unit<0>.triggerMatchCountWidth<0><0>=0
Project.unit<0>.triggerMatchType<0><0>=1
Project.unit<0>.triggerPortCount=1
Project.unit<0>.triggerPortIsData<0>=true
Project.unit<0>.triggerPortWidth<0>=1
Project.unit<0>.triggerSequencerLevels=16
Project.unit<0>.triggerSequencerType=1
Project.unit<0>.type=ilapro
