
 
 
 




rem Clean up the results directory
rmdir /S /Q results
mkdir results

rem Synthesize the VHDL Wrapper Files


echo 'Synthesizing example design with XST';
xst -ifn xst.scr
copy i2c_mem_exdes.ngc .\results\


rem Copy the netlist generated by Coregen
echo 'Copying files from the netlist directory to the results directory'
copy ..\..\i2c_mem.ngc results\


rem  Copy the constraints files generated by Coregen
echo 'Copying files from constraints directory to results directory'
copy ..\example_design\i2c_mem_exdes.ucf results\

cd results

echo 'Running ngdbuild'
<<<<<<< HEAD
ngdbuild -p xc4vsx25-ff668-10 i2c_mem_exdes
=======
ngdbuild -p xc3s1200e-fg320-4 i2c_mem_exdes
>>>>>>> merge_1

echo 'Running map'
map i2c_mem_exdes -o mapped.ncd  -pr i

echo 'Running par'
par mapped.ncd routed.ncd

echo 'Running trce'
trce -e 10 routed.ncd mapped.pcf -o routed

echo 'Running design through bitgen'
bitgen -w routed

echo 'Running netgen to create gate level VHDL model'
netgen -ofmt vhdl -sim -tm i2c_mem_exdes -pcf mapped.pcf -w routed.ncd routed.vhd
