#ChipScope Core Inserter Project File Version 3.0
#Tue Nov 11 21:29:23 CET 2025
Project.device.designInputFile=/home/user/_WORKSPACE_/kedziorno/mlx90640_fpga/xilinx_ise_14.7/test1_cs.ngc
Project.device.designOutputFile=/home/user/_WORKSPACE_/kedziorno/mlx90640_fpga/xilinx_ise_14.7/test1_cs.ngc
Project.device.deviceFamily=14
Project.device.enableRPMs=true
Project.device.outputDirectory=/home/user/_WORKSPACE_/kedziorno/mlx90640_fpga/xilinx_ise_14.7/_ngo
Project.device.useSRL16=true
Project.filter.dimension=19
Project.filter<0>=*_acpsubpage1*
Project.filter<10>=*reset*
Project.filter<11>=*do*
Project.filter<12>=*test_fixed_melexis_do*
Project.filter<13>=*float2fixedond*
Project.filter<14>=*float2fixedce*
Project.filter<15>=*recv*
Project.filter<16>=*ready*
Project.filter<17>=*doutb*
Project.filter<18>=*ena_2
Project.filter<1>=
Project.filter<2>=*i_acpsubpage0*
Project.filter<3>=*_do*
Project.filter<4>=*mux_*
Project.filter<5>=*clock*
Project.filter<6>=*i2c_mlx*
Project.filter<7>=*ena*
Project.filter<8>=*i2c_mlx_doutb*
Project.filter<9>=*i2c_mlx_enb*
Project.icon.boundaryScanChain=1
Project.icon.enableExtTriggerIn=false
Project.icon.enableExtTriggerOut=false
Project.icon.triggerInPinName=
Project.icon.triggerOutPinName=
Project.unit.dimension=1
Project.unit<0>.clockChannel=i_clock_BUFGP
Project.unit<0>.clockEdge=Rising
Project.unit<0>.dataChannel<0>=melexis_mlx9064x_core_inst inst_CalculateAlphaComp i_acpsubpage1<0>
Project.unit<0>.dataChannel<10>=melexis_mlx9064x_core_inst inst_CalculateAlphaComp i_acpsubpage1<10>
Project.unit<0>.dataChannel<11>=melexis_mlx9064x_core_inst inst_CalculateAlphaComp i_acpsubpage1<11>
Project.unit<0>.dataChannel<12>=melexis_mlx9064x_core_inst inst_CalculateAlphaComp i_acpsubpage1<12>
Project.unit<0>.dataChannel<13>=melexis_mlx9064x_core_inst inst_CalculateAlphaComp i_acpsubpage1<13>
Project.unit<0>.dataChannel<14>=melexis_mlx9064x_core_inst inst_CalculateAlphaComp i_acpsubpage1<14>
Project.unit<0>.dataChannel<15>=melexis_mlx9064x_core_inst inst_CalculateAlphaComp i_acpsubpage1<15>
Project.unit<0>.dataChannel<16>=melexis_mlx9064x_core_inst inst_CalculateAlphaComp i_acpsubpage1<16>
Project.unit<0>.dataChannel<17>=melexis_mlx9064x_core_inst inst_CalculateAlphaComp i_acpsubpage1<17>
Project.unit<0>.dataChannel<18>=melexis_mlx9064x_core_inst inst_CalculateAlphaComp i_acpsubpage1<18>
Project.unit<0>.dataChannel<19>=melexis_mlx9064x_core_inst inst_CalculateAlphaComp i_acpsubpage1<19>
Project.unit<0>.dataChannel<1>=melexis_mlx9064x_core_inst inst_CalculateAlphaComp i_acpsubpage1<1>
Project.unit<0>.dataChannel<20>=melexis_mlx9064x_core_inst inst_CalculateAlphaComp i_acpsubpage1<20>
Project.unit<0>.dataChannel<21>=melexis_mlx9064x_core_inst inst_CalculateAlphaComp i_acpsubpage1<21>
Project.unit<0>.dataChannel<22>=melexis_mlx9064x_core_inst inst_CalculateAlphaComp i_acpsubpage1<22>
Project.unit<0>.dataChannel<23>=melexis_mlx9064x_core_inst inst_CalculateAlphaComp i_acpsubpage1<23>
Project.unit<0>.dataChannel<24>=melexis_mlx9064x_core_inst inst_CalculateAlphaComp i_acpsubpage1<24>
Project.unit<0>.dataChannel<25>=melexis_mlx9064x_core_inst inst_CalculateAlphaComp i_acpsubpage1<25>
Project.unit<0>.dataChannel<26>=melexis_mlx9064x_core_inst inst_CalculateAlphaComp i_acpsubpage1<26>
Project.unit<0>.dataChannel<27>=melexis_mlx9064x_core_inst inst_CalculateAlphaComp i_acpsubpage1<27>
Project.unit<0>.dataChannel<28>=melexis_mlx9064x_core_inst inst_CalculateAlphaComp i_acpsubpage1<28>
Project.unit<0>.dataChannel<29>=melexis_mlx9064x_core_inst inst_CalculateAlphaComp i_acpsubpage1<29>
Project.unit<0>.dataChannel<2>=melexis_mlx9064x_core_inst inst_CalculateAlphaComp i_acpsubpage1<2>
Project.unit<0>.dataChannel<30>=melexis_mlx9064x_core_inst inst_CalculateAlphaComp i_acpsubpage1<30>
Project.unit<0>.dataChannel<31>=melexis_mlx9064x_core_inst inst_CalculateAlphaComp i_acpsubpage1<31>
Project.unit<0>.dataChannel<3>=melexis_mlx9064x_core_inst inst_CalculateAlphaComp i_acpsubpage1<3>
Project.unit<0>.dataChannel<4>=melexis_mlx9064x_core_inst inst_CalculateAlphaComp i_acpsubpage1<4>
Project.unit<0>.dataChannel<5>=melexis_mlx9064x_core_inst inst_CalculateAlphaComp i_acpsubpage1<5>
Project.unit<0>.dataChannel<6>=melexis_mlx9064x_core_inst inst_CalculateAlphaComp i_acpsubpage1<6>
Project.unit<0>.dataChannel<7>=melexis_mlx9064x_core_inst inst_CalculateAlphaComp i_acpsubpage1<7>
Project.unit<0>.dataChannel<8>=melexis_mlx9064x_core_inst inst_CalculateAlphaComp i_acpsubpage1<8>
Project.unit<0>.dataChannel<9>=melexis_mlx9064x_core_inst inst_CalculateAlphaComp i_acpsubpage1<9>
Project.unit<0>.dataDepth=65536
Project.unit<0>.dataEqualsTrigger=false
Project.unit<0>.dataPortWidth=32
Project.unit<0>.enableGaps=false
Project.unit<0>.enableStorageQualification=true
Project.unit<0>.enableTimestamps=false
Project.unit<0>.timestampDepth=0
Project.unit<0>.timestampWidth=0
Project.unit<0>.triggerChannel<0><0>=i_clock_BUFGP
Project.unit<0>.triggerConditionCountWidth=0
Project.unit<0>.triggerMatchCount<0>=1
Project.unit<0>.triggerMatchCountWidth<0><0>=16
Project.unit<0>.triggerMatchType<0><0>=7
Project.unit<0>.triggerPortCount=1
Project.unit<0>.triggerPortIsData<0>=true
Project.unit<0>.triggerPortWidth<0>=1
Project.unit<0>.triggerSequencerLevels=16
Project.unit<0>.triggerSequencerType=1
Project.unit<0>.type=ilapro
