#ChipScope Core Inserter Project File Version 3.0
#Sun Nov 09 21:26:45 CET 2025
Project.device.designInputFile=/home/user/_WORKSPACE_/kedziorno/mlx90640_fpga/xilinx_ise_14.7/test1_cs.ngc
Project.device.designOutputFile=/home/user/_WORKSPACE_/kedziorno/mlx90640_fpga/xilinx_ise_14.7/test1_cs.ngc
Project.device.deviceFamily=14
Project.device.enableRPMs=true
Project.device.outputDirectory=/home/user/_WORKSPACE_/kedziorno/mlx90640_fpga/xilinx_ise_14.7/_ngo
Project.device.useSRL16=true
Project.filter.dimension=19
Project.filter<0>=*sr*
Project.filter<10>=*ready*
Project.filter<11>=*read*
Project.filter<12>=*melexis_mlx90640_i2c_mode2_ready*
Project.filter<13>=*melexis_mlx90640_i2c_bytes_to_recv*
Project.filter<14>=*latch*
Project.filter<15>=*o_ready*
Project.filter<16>=*latch_data*
Project.filter<17>=*i2c_mlx_*
Project.filter<18>=*i2c_mem*
Project.filter<1>=**
Project.filter<2>=*scl*
Project.filter<3>=
Project.filter<4>=*doutb*
Project.filter<5>=*ena_2*
Project.filter<6>=*ea_2*
Project.filter<7>=*clock*
Project.filter<8>=*ena*
Project.filter<9>=*recv*
Project.icon.boundaryScanChain=1
Project.icon.enableExtTriggerIn=false
Project.icon.enableExtTriggerOut=false
Project.icon.triggerInPinName=
Project.icon.triggerOutPinName=
Project.unit.dimension=1
Project.unit<0>.clockChannel=scl_o
Project.unit<0>.clockEdge=Rising
Project.unit<0>.dataChannel<0>=melexis_mlx90640_i2c_i0 bytes_to_recv_sr<0>
Project.unit<0>.dataChannel<10>=melexis_mlx90640_i2c_i0 bytes_to_recv_sr<10>
Project.unit<0>.dataChannel<11>=melexis_mlx90640_i2c_i0 bytes_to_recv_sr<11>
Project.unit<0>.dataChannel<12>=melexis_mlx90640_i2c_i0 bytes_to_recv_sr<12>
Project.unit<0>.dataChannel<13>=melexis_mlx90640_i2c_i0 bytes_to_recv_sr<13>
Project.unit<0>.dataChannel<14>=melexis_mlx90640_i2c_i0 bytes_to_recv_sr<14>
Project.unit<0>.dataChannel<15>=melexis_mlx90640_i2c_i0 bytes_to_recv_sr<15>
Project.unit<0>.dataChannel<16>=melexis_mlx90640_i2c_i0 bytes_to_recv_sr<16>
Project.unit<0>.dataChannel<1>=melexis_mlx90640_i2c_i0 bytes_to_recv_sr<1>
Project.unit<0>.dataChannel<2>=melexis_mlx90640_i2c_i0 bytes_to_recv_sr<2>
Project.unit<0>.dataChannel<3>=melexis_mlx90640_i2c_i0 bytes_to_recv_sr<3>
Project.unit<0>.dataChannel<4>=melexis_mlx90640_i2c_i0 bytes_to_recv_sr<4>
Project.unit<0>.dataChannel<5>=melexis_mlx90640_i2c_i0 bytes_to_recv_sr<5>
Project.unit<0>.dataChannel<6>=melexis_mlx90640_i2c_i0 bytes_to_recv_sr<6>
Project.unit<0>.dataChannel<7>=melexis_mlx90640_i2c_i0 bytes_to_recv_sr<7>
Project.unit<0>.dataChannel<8>=melexis_mlx90640_i2c_i0 bytes_to_recv_sr<8>
Project.unit<0>.dataChannel<9>=melexis_mlx90640_i2c_i0 bytes_to_recv_sr<9>
Project.unit<0>.dataDepth=131072
Project.unit<0>.dataEqualsTrigger=false
Project.unit<0>.dataPortWidth=17
Project.unit<0>.enableGaps=false
Project.unit<0>.enableStorageQualification=true
Project.unit<0>.enableTimestamps=false
Project.unit<0>.timestampDepth=0
Project.unit<0>.timestampWidth=0
Project.unit<0>.triggerChannel<0><0>=scl_o
Project.unit<0>.triggerChannel<0><1>=i2c_mlx_doutb<1>
Project.unit<0>.triggerChannel<0><2>=i2c_mlx_doutb<2>
Project.unit<0>.triggerChannel<0><3>=i2c_mlx_doutb<3>
Project.unit<0>.triggerChannel<0><4>=i2c_mlx_doutb<4>
Project.unit<0>.triggerChannel<0><5>=i2c_mlx_doutb<5>
Project.unit<0>.triggerChannel<0><6>=i2c_mlx_doutb<6>
Project.unit<0>.triggerChannel<0><7>=i2c_mlx_doutb<7>
Project.unit<0>.triggerConditionCountWidth=0
Project.unit<0>.triggerMatchCount<0>=1
Project.unit<0>.triggerMatchCountWidth<0><0>=16
Project.unit<0>.triggerMatchType<0><0>=7
Project.unit<0>.triggerPortCount=1
Project.unit<0>.triggerPortIsData<0>=true
Project.unit<0>.triggerPortWidth<0>=1
Project.unit<0>.triggerSequencerLevels=16
Project.unit<0>.triggerSequencerType=1
Project.unit<0>.type=ilapro
